devwork

diff --git a/install b/install
--- a/install
+++ b/install
@@ -104,8 +104,6 @@ fi
 
 echo "[*] Installing Metasploit Framework..."
 
-echo "[*] Downloading..."
-
 {
   curl -s https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && chmod +x ./msfinstall && ./msfinstall 2>&1>/dev/null
 } 2>&1 > /dev/null
@@ -114,14 +112,22 @@ if [ $? -eq 0 ]; then
   echo "[+] Metasploit installed successfully."
   rm ./msfinstall
 else
-  echo "[-] Metasploit failed to install. Leaving msfinstall file for troubleshooting purposes."
+  echo "[-] Metasploit failed to install. Retrying with verbose output..."
+  ./msfinstall
+
+  if [ $? -eq 0 ]; then 
+    echo "[+] Metasploit installed successfully."
+    rm ./msfinstall
+  else
+    echo "[-] Metasploit failed to install again. Leaving msfinstall file for troubleshooting."
+    rm ./msfinstall
+  fi
 fi
 
+echo "[*] Installing Bruno..."
+
 {
-  mkdir -p /etc/apt/keyrings && gpg --no-default-keyring --keyring /etc/apt/keyrings/bruno.gpg --keyserver keyserver.ubuntu.com --recv-keys 9FA6017ECABE0266 && echo "deb [signed-by=/etc/apt/keyrings/bruno.gpg] http://debian.usebruno.com/ bruno stable" | sudo tee /etc/apt/sources.list.d/bruno.list 
-  
-  sudo apt update 
-  sudo apt install bruno
+  wget https://github.com/usebruno/bruno/releases/download/v1.28.0/bruno_1.28.0_amd64_linux.deb -O bruno_1.28.0_amd64_linux.deb && apt install ./bruno_1.28.0_amd64_linux.deb
 } 2>&1 > /dev/null
 
 if [ $? -eq 0 ]; then
