added more structure via comments and added nmap install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,6 +1,8 @@
 #!/bin/bash
 # Written by Draztick
 
+########  Update Section  ##############
+
 echo "[*] Updating repositories..."
 
 {
@@ -25,3 +27,30 @@ else
   echo "[-] Packages failed to upgrade."
 fi
 
+########  In repo installs  ###############
+
+echo "[*] Installing Nmap..."
+
+{ apt install nmap -y } 2>&1 > /dev/null
+
+if [ $? -eq 0 ]; then
+  echo "[+] Nmap installed successfully."
+else
+  echo "[-] Nmap failed to install."
+fi
+
+
+########  Make necessary directories  #############
+
+
+
+
+
+
+####### Manual installs ############
+
+
+
+
+
+########  Linking  #############
