updated the update command and added the upgrade command.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,10 +1,27 @@
 #!/bin/bash
 # Written by Draztick
 
-echo "Updating..."
+echo "Updating repositories..."
 
 {
-  apt update && apt upgrade -y
-} > 1&>/dev/null 2&>/dev/null
+  apt update 2>/dev/null 
+} 2>&1 > /dev/null
 
-echo $?
+if [ $? -eq 0 ]; then
+  echo "[+] Repositories updated successfully."
+else
+  echo "[-] Repositories failed to update."
+fi
+
+echo "Updating packages..."
+
+{
+  apt upgrade -y 2>/dev/null
+} 2>&1 > /dev/null
+
+if [ $? -eq 0 ]; then
+  echo "[+] Packages upgrade successfully."
+else
+  echo "[-] Packages failed to upgrade."
+fi
+
